openapi: 3.0.1
info:
  title: User API
  description: Operations related to users
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local Server

paths:
  /users:
    get:
      tags:
        - swiggy #required to create name as SwiggyApi in place of DefaultApi
      summary: Get all users
      operationId: getAllUsers
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserDto"
    post:
      tags:
        - swiggy
      summary: Create a new user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDto"
      responses:
        "201":
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDto"

  /users/{id}:
    get:
      tags:
        - swiggy
      summary: Get user by ID
      operationId: getUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: User found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDto"
        "404":
          description: User not found

components:
  schemas:
    UserDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string

